services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
#    build:
#      context: .
#      dockerfile: ./docker/golang.Dockerfile
    container_name: whatsapp
    restart: always
    ports:
      - ":3000"
    volumes:
      - whatsapp:/app/storages
    command:
      - --basic-auth=admin:admin
      - --port=3000
      - --debug=true
      - --os=EmpatIA
      - --account-validation=false

volumes:
  whatsapp:
